from playlist_forge.actions import merge_playlists
from playlist_forge.models import Track


def test_merge_deduplicates_by_spotify_id_and_isrc(monkeypatch):
    captured: dict = {}

    def fake_create_playlist(_spotify, name, track_ids, **kwargs):
        captured["name"] = name
        captured["track_ids"] = track_ids
        captured.update(kwargs)
        return "new-playlist"

    monkeypatch.setattr(merge_playlists.spotify_client, "create_playlist", fake_create_playlist)
    tracks = [
        Track(spotify_id="first", title="First", artist="A", album="", isrc="same"),
        Track(spotify_id="duplicate-id", title="Duplicate", artist="A", album=""),
        Track(spotify_id="duplicate-id", title="Duplicate", artist="A", album=""),
        Track(spotify_id="duplicate-isrc", title="Other", artist="B", album="", isrc="same"),
        Track(spotify_id="unique", title="Unique", artist="C", album="", isrc="different"),
    ]

    result = merge_playlists.merge(object(), tracks, "Merged", ["One", "Two"])

    assert result == "new-playlist"
    assert captured["name"] == "Merged"
    assert captured["track_ids"] == ["first", "duplicate-id", "unique"]
    assert captured["description"] == "Generated by playlist-forge. Merged from: One, Two."
