"""Turn `analyze cluster` output into real Spotify playlists."""

from __future__ import annotations

from collections import defaultdict

import spotipy

from .. import spotify_client


def create_from_clusters(
    spotify: spotipy.Spotify,
    tracks: list,
    name_prefix: str = "Auto-",
    skip_noise: bool = True,
    dry_run: bool = False,
) -> dict[int, str | None]:
    """Create one playlist per cluster ID from clustered tracks.

    Args:
        spotify: Authenticated Spotify API client.
        tracks: Tracks that may contain ``cluster_id`` assignments.
        name_prefix: Prefix used for generated playlist names.
        skip_noise: Whether to skip tracks with ``cluster_id == -1``.
        dry_run: Whether to skip API writes and only print actions.

    Returns:
        Mapping of cluster ID to created playlist ID, or None for dry-run entries.
    """
    by_cluster: dict[int, list[str]] = defaultdict(list)
    for t in tracks:
        if t.cluster_id is None:
            continue
        if skip_noise and t.cluster_id == -1:
            continue
        by_cluster[t.cluster_id].append(t.spotify_id)

    created: dict[int, str | None] = {}
    for cluster_id, track_ids in sorted(by_cluster.items()):
        name = f"{name_prefix}Cluster {cluster_id}"
        playlist_id = spotify_client.create_playlist(
            spotify, name, track_ids,
            description=f"Generated by playlist-forge from cluster {cluster_id} "
                        f"({len(track_ids)} tracks).",
            dry_run=dry_run,
        )
        created[cluster_id] = playlist_id
    return created
