"""Turn `analyze cluster` output into real Spotify playlists."""

from __future__ import annotations

from collections import defaultdict

import spotipy

from .. import spotify_client


def create_from_clusters(
    spotify: spotipy.Spotify,
    tracks: list,
    name_prefix: str = "Auto-",
    skip_noise: bool = True,
    dry_run: bool = False,
) -> dict[int, str | None]:
    """One playlist per cluster_id. Skips cluster_id == -1 (HDBSCAN noise /
    "doesn't belong anywhere") by default — those tracks are candidates for
    manual review, not a playlist of their own.
    """
    by_cluster: dict[int, list[str]] = defaultdict(list)
    for t in tracks:
        if t.cluster_id is None:
            continue
        if skip_noise and t.cluster_id == -1:
            continue
        by_cluster[t.cluster_id].append(t.spotify_id)

    created: dict[int, str | None] = {}
    for cluster_id, track_ids in sorted(by_cluster.items()):
        name = f"{name_prefix}Cluster {cluster_id}"
        playlist_id = spotify_client.create_playlist(
            spotify, name, track_ids,
            description=f"Generated by playlist-forge from cluster {cluster_id} "
                        f"({len(track_ids)} tracks).",
            dry_run=dry_run,
        )
        created[cluster_id] = playlist_id
    return created
