"""Merge two or more existing playlists into one new playlist."""

from __future__ import annotations

import spotipy

from .. import spotify_client


def merge(
    spotify: spotipy.Spotify,
    tracks: list,
    into_name: str,
    playlist_names: list[str] | None = None,
    dedupe_by_isrc: bool = True,
    dry_run: bool = False,
) -> str | None:
    """Create a new playlist containing all of the specified tracks.

    Args:
        spotify: Authenticated Spotify API client.
        tracks: Tracks to include in the new playlist.
        into_name: Name for the new merged playlist.
        playlist_names: Optional list of names of the playlists being merged.
        dedupe_by_isrc: Whether to drop duplicate ISRC matches.
        dry_run: Whether to skip API writes and only print actions.

    Returns:
        Created playlist ID, or None in dry-run mode.
    """
    merged_from = ', '.join(playlist_names) if playlist_names else "all playlists"
    seen_ids: set[str] = set()
    seen_isrcs: set[str] = set()
    track_ids: list[str] = []
    for t in tracks:
        if t.spotify_id in seen_ids:
            continue
        if dedupe_by_isrc and t.isrc and t.isrc in seen_isrcs:
            continue
        seen_ids.add(t.spotify_id)
        if t.isrc:
            seen_isrcs.add(t.isrc)
        track_ids.append(t.spotify_id)

    return spotify_client.create_playlist(
        spotify, into_name, track_ids,
        description=f"Generated by playlist-forge. Merged from: {merged_from}.",
        dry_run=dry_run,
    )
