"""Merge two or more existing playlists into one new playlist."""

from __future__ import annotations

import spotipy

from .. import spotify_client


def merge(
    spotify: spotipy.Spotify,
    tracks: list,
    into_name: str,
    playlist_names: list[str] | None = None,
    dry_run: bool = False,
) -> str | None:
    """Create a new playlist containing all of the specified tracks.

    Args:
        spotify: Authenticated Spotify API client.
        tracks: Tracks to include in the new playlist.
        into_name: Name for the new merged playlist.
        dry_run: Whether to skip API writes and only print actions.

    Returns:
        Created playlist ID, or None in dry-run mode.
    """
    merged_from = ', '.join(playlist_names) if playlist_names else "all playlists"

    return spotify_client.create_playlist(
        spotify, into_name, [t.spotify_id for t in tracks],
        description=f"Generated by playlist-forge. Merged from: {merged_from}.",
        dry_run=dry_run,
    )
